### ISSUE TITLE
Methods checklist

### ISSUE THREAD

**Issue by davidagold** [JuliaStats/NullableArrays.jl#9]
This issue contains an in-progress checklist of methods that ought to be implemented for NullableArrays.
### Outer Constructors
- [ ] NullableArray{T, N}(A::AbstractArray{T, N}, m::Array{Bool, N})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] NullableArray{T, N}(A::AbstractArray{T, N})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] NullableArray{T}(::Type{T}, dims::Dims)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] NullableArray(T::Type, dims::Int...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] NullableArray{T, U}(A::AbstractArray, ::Type{T}, ::Type{U})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] NullableArray{T}(A::AbstractArray, ::Type{T}, na::Any; conversion::Base.Callable=Base.convert)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.call{T, N}(::Type{NullableArray{T, N}})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
### Primitives
- [ ] Base.size(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.similar{T <: Nullable}(X::NullableArray, ::Type{T}, dims::Dims)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.similar(X::NullableArray, T, dims::Dims)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.copy!(dest::NullableArray, src::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.copy(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.fill!(X::NullableArray, x::Nullable)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.fill!(X::NullableArray, x::Any)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.deepcopy(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.resize!{T}(X::NullableArray{T, 1}, n::Int)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.ndims(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.length(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.endof(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.find(X::NullableArray{Bool})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] dropnull(X::NullableVector)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] ~~Base.isnull(X::NullableArray)~~
  - [x] implemente
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Nixed in https://github.com/johnmyleswhite/NullableArrays.jl/commit/5dcfbe06af6a77c16b0ae2f2a271e9dec2fe6973
- [ ] ~~Base.isnull(X::NullableArray, i::Integer)~~
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Nixed in https://github.com/johnmyleswhite/NullableArrays.jl/commit/5dcfbe06af6a77c16b0ae2f2a271e9dec2fe6973
- [ ] ~~Base.isnull(X::NullableArray I::Any...)~~
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Nixed in https://github.com/johnmyleswhite/NullableArrays.jl/commit/5dcfbe06af6a77c16b0ae2f2a271e9dec2fe6973
- [ ] anynull(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] anynull(xs::NTuple)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] allnull(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.isnan(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.isfinite(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{S, T, N}(::Type{Array{S, N}, X::NullableArray{T, N})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{S, T, N}(::Type{Array{S}}, X::NullableArray{T, N})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{T}(::Type{Vector}, X::NullableVector{T})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{T}(::Type{Matrix}, X::NullableMatrix{T})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{T, N}(::Type{Array}, X::NullableArray{T, N})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{S, T, N}(::Type{Array{S, N}}, X::NullableArray{T, N}, replacement::Any)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{T}(::Type{Vector}, X::NullableVector{T}, replacement::Any)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{T}(::Type{Matrix}, X::NullableMatrix{T}, replacement::Any)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{T, N}(::Type{Array}, X::NullableArray{T, N}, replacement::Any)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{S, T, N}(::Type{NullableArray{S, N}}, A::AbstractArray{T, N})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{S, T, N}(::Type{NullableArray{S}}, A::AbstractArray{T, N})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert(::Type{NullableArray}, A::AbstractArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.convert{S, T, N}(::Type{NullableArray{S, N}, A::NullableArray{T, N})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.float(X::NullableArray)
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.round(Int, X::NullableArray)
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.bool(X::NullableArray)
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
### Indexing
- [ ] Base.linearindexing{T<:NullableArray}(::Type{T})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.getindex{T, N}(X::NullableArray{T, N}, I::Int...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.getindex{T, N}(X::NullableArray{T, N}, I::Nullable{Int}...)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.setindex!(X::NullableArray, v::Nullable, I::Int...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.setindex!(X::NullableArray, v::Any, I::Int...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] unsafe_getindex_notnull(X::NullableArray, I::Int...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] unsafe_getvalue_notnull(X::NullableArray, I::Int...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base._checkbounds{T<:Real}(sz::Int, x::Nullable{T})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base._checkbounds(sz::Int, I::NullableVector{Bool})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base._checkbounds{T<:Real}(sz::Int, I::NullableArray{T})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.to_index(X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] nullify!(X::NullableArray, I...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
### Map
- [ ] Base.map!{F}(f::F, X::NullableArray, A::AbstractArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.map!{F}(f::F, X::NullableArray, A::AbstractArray, B::AbstractArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Entirely lacking coverage (7/1/15)
- [ ] Base.map!{F}(f::F, X::NullableArray, As...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.map(f::Function, X::NullableArray)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.map(f::Function, X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Lacking coverage on a single line (7/1/15)
- [ ] Base.map(f::Function, Xs::NullableArray...)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Lacking coverage on a single line (7/1/15)
### Broadcast
- [ ] Base.broadcast!(f::Function, X::NullableArray, As...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes: inherited from base/broadcast.jl
- [ ] Base.broadcast(f::Function, As...)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes: inherited from base/broadcast.jl
- [ ] Base.(:(.+))(As...)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.-))(A, B)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.*))(As...)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(./))(A, B)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.%))(A, B)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.))(A, B)
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.^))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.^))(X::NullableArray, A::AbstractArray)
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Ought we to implement this method? Might go against lifting paradigm...
- [ ] Base.(:(.^))(A::AbstractArray, Y::NullableArray)
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Ought we to implement this method? Might go against lifting paradigm...
- [ ] Base.(:(.^))(A::BitArray, Y::NullableArray)
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Ought we to implement this method? Might go against lifting paradigm...
- [ ] Base.(:(.^))(A::AbstractArray{Bool}, Y::NullableArray}
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Ought we to implement this method? Might go against lifting paradigm...
- [ ] Base.(:(.^))(X::NullableArray, B::BitArray)
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Ought we to implement this method? Might go against lifting paradigm...
- [ ] Base.(:(.^))(X::NullableArray, B::AbstractArray{Bool})
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Ought we to implement this method? Might go against lifting paradigm...
- [ ] Base.(:(.==))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.!=))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.<))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.>))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.<=))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.>=))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.>>))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.(:(.<<))(X::NullableArray, Y::NullableArray)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
### Matrix methods
- [ ] Base.diag{T}(M::NullableMatrix{T})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes: inherited from `linalg/dense.jl`
### Vector methods
- [ ] head(X::NullableVector)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] tail(X::NullableVector)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.push!{T, U}(X::NullableVector, v::Nullable{U})
  - [x] implemented
  - [ ] tested 
  - [ ] profiled
  - [ ] documented
  - Notes: A portion of the method source code currently lacks test coverage (7/1/15). 
- [ ] Base.push!{T, U}(X::NullableVector{T}, v::U)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.pop!{T}(X::NullableVector{T})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.unshift!{T, U}(X::NullableVector{T}, v::Nullable{U})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.unshift!{T, U}(X::NullableVector{T}, v::U}
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.shift!{T}(X::NullableVector{T})
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.splice!(X::NullableVector, inds::Union{Integer, UnitRange{Int}})
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: A portion of the method source code currently lacks test coverage (7/1/15).
- [ ] Base.splice!(X::NullableVector, inds::Union{Integer, UnitRange{Int}}, ins::AbstractVector)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.deleteat!(X::NullableVector, inds)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] ~~Base.map(f::Function, NullableVector)~~
  - [ ] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Redundant -- see "Map" section above
- [ ] Base.append!(X::NullableVector, items::AbstractVector)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.sizehint!(X::NullableVector, newsz)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: Current test coverage just makes sure that calling the method doesn't throw an error. I don't know what is an appropriate way to check that the method actually works.
- [ ] padnull(X::NullableVector, front::Integer, back::Integer)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] padnull!{T}(X::NullableVector{T}, front::Integer, back::Integer)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.reverse!(X::NullableVector, s, n)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: A portion of the method source code currently lacks test coverage (7/1/15).
    Base.reverse(X::NullableVector, s, n)
  - [x] implemented
  - [x] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
### Reduce
- [ ] Base.mapreduce(f, op::Function, X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.mapreduce(f, op, X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.reduce(op, X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.sum(f::Union{Function, Base.Func{1}}, X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.sum(X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.prod(f::Union{Function, Base.Func{1}}, X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.prod(X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.minimum(f::Union{Function, Base.Func{1}}, X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.minimum(X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.maximum(f::Union{Function, Base.Func{1}}, X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.maximum(X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.sumabs(X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.sumabs2(X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.mean(X::NullableArray, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.mean{W, V}(X::NullableArray, w::WeightVec{W, V}; skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.mean{W, V<:NullableArray}(X::NullableArray, w::WeightVec{W, V}; skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.varm{T}(X::NullableArray{T}, m::Number; corrected::Bool, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.varm{T}(X::NullableArray, m::Nullable{T}; corrected::Bool, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes: 
- [ ] Base.varzm{T}(X::NullableArray; corrected::Bool, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.var(X::NullableArray; corrected::Bool, mean::Any, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.stdm(X::NullableArray, m::Number; corrected::Bool, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
- [ ] Base.std(X::NullableArray; corrected::Bool, mean::Any, skipnull::Bool)
  - [x] implemented
  - [ ] tested
  - [ ] profiled
  - [ ] documented
  - Notes:
